language: java

services:
  - docker

before_install:
  - echo -n "*** LIFECYCLE STARTED - 'before_install' *****************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - before_install *****************************************************************"

install:
  - echo "*** LIFECYCLE STARTED - 'install' ***************************************************************************"
  - echo "*** LIFECYCLE COMPLETED - 'install' *************************************************************************"

before_script:
  - echo -n "*** LIFECYCLE STARTED - 'before_script' ******************************************************************"
  - npm run clean && npm run lint && npm run build && npm run docs
  - echo -n "*** LIFECYCLE COMPLETED - 'before_script' ****************************************************************"

script:
  - echo -n "*** LIFECYCLE STARTED - 'script' *************************************************************************"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t paulscherrerinstitute/wica-js:latest -f docker/Dockerfile .
  - docker push paulscherrerinstitute/wica-js:latest
  - echo -n "LIFECYCLE COMPLETED - 'script' ***************************************************************************"

after_script:
  - echo -n "*** LIFECYCLE STARTED - 'after_script' *******************************************************************"
  - echo -n "*** LIFECYCLE COMPLETED - 'after_script' *****************************************************************"

