###############################################################################
# Travis file to support automatic build and deployment of Wica-JS Artifacts
###############################################################################

#
# This build recipe should be set up to trigger every time new TAGGED commits
# are pushed to the Wica-JS repository in the PSI Organisational Area on the
# GitHub Server.
#
# Currently the build recipe supports the following actions:
#
# - Builds Wica-JS API documentation and transfers asset to GitHub Pages Area.
# - Builds Wica-JS Release Bundle and transfers asset to GitHub Releases Area.
# - Builds Wica-JS Docker Image and transfers asset to Docker Hub.
#

# *******************************************
# Build Environment Configuration Starts Here
# *******************************************

# The Node environment is required to perform the Wica-JS release bundling.
language: node_js
node_js:
  - "10"

# The Docker environment is required to run the Dockerfile and to push the release to Docker Hub.
services:
  - docker

# *******************************************
# Build Lifecycle Handling Starts Here
# *******************************************

# before_install:
#  - echo -n "*** LIFECYCLE STARTED - 'before_install' *****************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - before_install *****************************************************************"

install:
  - echo "*** LIFECYCLE STARTED - 'install' ***************************************************************************"
  - npm install                               # Install the dependencies expressed in the node 'package.json' file.
  - echo "*** LIFECYCLE COMPLETED - 'install' *************************************************************************"

# before_script:
#  - echo -n "*** LIFECYCLE STARTED - 'before_script' ******************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - 'before_script' ****************************************************************"

script:
  - echo -n "*** LIFECYCLE STARTED - 'script' *************************************************************************"
  - npm run clean && npm run lint && npm run build && npm run docs && npm run zip
  - echo -n "*** LIFECYCLE COMPLETED - 'script' ***********************************************************************"

# before_deploy:
#  - echo -n "*** LIFECYCLE STARTED - 'before_deploy' ******************************************************************"
#  - echo -n "LIFECYCLE COMPLETED - 'before_deploy' ********************************************************************"

# The Travis Lifecycle 'deploy' phase is optional and runs after the Travis Lifecycle 'script' phase has completed.
deploy:
  # Copy the Wics-JS release asset into the GitHub Releases Area.
  - provider: releases                       # Travis GitHub Release Area Provider.
    skip_cleanup: true                       # Set to true in accordance with Travis GitHub Releases Provider docs.
    api_key:                                 # See the Travis documnetation for how this key was created.
      secure:  "Bge4uy7y+wAYie0MV8xuuvdReY5vWwJJNFTyvaNqkB2LcUq+zziVUoklV4Pqt1y5Z5COuZVSKwwwLlrnrluQB1sLxcYg910z9WJ7nl0aXekzQRKM5EpFfv/blDyNPQnBjeQCce/KBmhRyLMki9S7nVGGGLeY/U1a01CCQwl3DRzkAnnkbyyee5d1igia1uG8K+x7K65dnN+sdkuG/MCWs70H29D/Kii/zBQHdaomtbTplli+yaRJLhKeKd4yQCfi39IOFxkFRXmKxrw5AKKVuGPYWNlZV6Q9Ow+XW/q2jCqLnaGL6Km8PzijOCYBjPUgNHo3uSXPjj86CHttamGejRaF9oZaA2aH7vojNbR+0cR4x56KH/XxrKZJCYg+yIrHeksF0tmmd95tbFv2Nvh4iIdZ09jqSOWWB7GlELcjb2+D3yToIXj4benR5O2AHA1rnTIzprr7PchHhMb3Sm/YziGR6N8JdN8JfkAFpp00yoBiJchd9KLIPEiAiI1IoGlS6eV37PIGthR9Nm0JAT8xd/qhgnjsWfk022jh3KAJ1nUQ4S715C/D+DrHMSZfiLud89guCgDSd84xOroliTFJSjgVI9beD+a2QlRbuVJV0QG9EqTyqt7GujsXX9i7XJjhfma2R/0M0wQ8rhXUI2FJHn2GydYX/SniWDuANwTws0o="
    file: dist/wica-js.zip                   # The asset to be deployed.
    draft: false                             # Create a GitHub Regular Release not a GitHub Draft.
    overwrite: true                          # Allow new LATEST releases to overwrite old ones.
    on:
      tags: true                             # Skip this deployment unless tagged.
      repo: paulscherrerinstitute/wica-js    # The GitHub Repository to operate on.
  # Copy the Wics-JS API documentation into the GitHub Pages Area.
  - provider: pages                          # Travis GitHub Pages Area Provider.
    local_dir: dist/api                      # The asset to be deployed.
    skip_cleanup: true                       # Set to true in accordance with Travis GitHub Pages Provider docs.
    github_token: $GITHUB_TOKEN              # Set in the settings page of your repository, as a secure variable.
    keep_history: true                       # Retain previous versions of the documentation.
    on:
      tags: true                             # Skip this deployment unless tagged.
      repo: paulscherrerinstitute/wica-js    # The GitHub Repository to operate on.

  # Log into Docker and run build
#  - provider: script
#    skip_cleanup: false
#    script:
#      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#      docker build -t paulscherrerinstitute/wica-js:latest -f docker/Dockerfile .
#      docker push paulscherrerinstitute/wica-js:latest

# after_script:
#  - echo -n "*** LIFECYCLE STARTED - 'after_script' *******************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - 'after_script' *****************************************************************"

