###############################################################################
# Travis file to support automatic build and deployment of Wica-JS Artifacts
###############################################################################

#
# This build recipe should be set up to trigger every time new TAGGED commits
# are pushed to the Wica-JS repository in the PSI Organisational Area on the
# GitHub Server.
#
# Currently the build recipe supports the following actions:
#
# - Builds Wica-JS API documentation and transfers asset to GitHub Pages Area.
# - Builds Wica-JS Release Bundle and transfers asset to GitHub Releases Area.
# - Builds Wica-JS Docker Image and transfers asset to Docker Hub.
#

# *******************************************
# Build Environment Configuration Starts Here
# *******************************************

# Only trigger this build recipe on tagged commits.
if: tag IS present


# The Node environment is required to perform the Wica-JS release bundling.
language: node_js
node_js:
  - "10"

# The Docker environment is required to run the Dockerfile and to push the release to Docker Hub.
services:
  - docker

# *******************************************
# Build Lifecycle Handling Starts Here
# *******************************************

# before_install:
#  - echo -n "*** LIFECYCLE STARTED - 'before_install' *****************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - before_install *****************************************************************"

install:
  - echo "*** LIFECYCLE STARTED - 'install' ***************************************************************************"
  - npm install                               # Install the dependencies expressed in the node 'package.json' file.
  - echo "*** LIFECYCLE COMPLETED - 'install' *************************************************************************"

# before_script:
#  - echo -n "*** LIFECYCLE STARTED - 'before_script' ******************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - 'before_script' ****************************************************************"

script:
  - echo -n "*** LIFECYCLE STARTED - 'script' *************************************************************************"
  - npm run clean && npm run lint && npm run build && npm run docs && npm run zip
  - echo -n "*** LIFECYCLE COMPLETED - 'script' ***********************************************************************"

# before_deploy:
#  - echo -n "*** LIFECYCLE STARTED - 'before_deploy' ******************************************************************"
#  - echo -n "LIFECYCLE COMPLETED - 'before_deploy' ********************************************************************"

# The Travis Lifecycle 'deploy' phase is optional and runs after the Travis Lifecycle 'script' phase has completed.

deploy:
  # Copy the Wics-JS release asset into the GitHub Releases Area.
  - provider: releases                       # Travis GitHub Releases Provider.
    edge: false                              # Stick with the old V1 Travis DPL support, not the new V2 support which
    skip_cleanup: true                       # Set to true in accordance with Travis GitHub Releases Provider docs.
    token: "$GITHUB_TOKEN"                   # Set in the settings page of your repository, as a secure variable.
    file: dist/wica-js.zip                   # The asset to be deployed.
    draft: false                             # Create a GitHub Regular Release not a GitHub Draft.
    overwrite: true                          # Allow new LATEST releases to overwrite old ones.
    on:
      tags: true                             # Skip this deployment unless $TRAVIS_TAG is set.

  # Copy the Wics-JS API documentation into the GitHub Pages Area.
  - provider: pages                          # Travis GitHub Pages Provider.
    local_dir: dist/apidocs                  # The asset to be deployed.
    skip_cleanup: true                       # Set to true in accordance with Travis GitHub Pages Provider docs.
    github_token: $GITHUB_TOKEN              # Set in the settings page of your repository, as a secure variable.
    keep_history: true                       # Retain previous versions of the documentation.
    on:
      tags: true                              # Skip this deployment unless $TRAVIS_TAG is set.

  # Log into Docker and run build
  - provider: script
    skip_cleanup: false
    script:
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker build -t paulscherrerinstitute/wica-js:$TRAVIS_TAG -t paulscherrerinstitute/wica-js:latest -f docker/Dockerfile . &&
      docker push paulscherrerinstitute/wica-js:$TRAVIS_TAG &&
      docker push paulscherrerinstitute/wica-js:latest
    on:
      tags: true                              # Skip this deployment unless $TRAVIS_TAG is set.

# after_script:
#  - echo -n "*** LIFECYCLE STARTED - 'after_script' *******************************************************************"
#  - echo -n "*** LIFECYCLE COMPLETED - 'after_script' *****************************************************************"

