' This is a Plant UML Sequence Diagram that illustrates the basic Wica Page Update Sequence.
' See here: http://plantuml.com/sequence-diagram for further information.

' Publication procedure is as follows:
' Copy and Paste contents of this page into the live editor here: http://plantuml.com/plantuml/uml/
' Obtain the SVG Link to the rendered image and shorten it using the TinyUrl Service here: https://tinyurl.com/
@startuml

participant "Browser"
participant "Web Page HTML"
participant "Web Page DOM"
participant "Wica-JS-Library"
participant "Wica-HTTP-Server"
participant "Control System"

hide footbox
skinparam sequenceMessageAlign center
skinparam monochrome true

group initialise
"Browser" -> "Web Page HTML" : load
"Browser" -> "Wica-JS-Library" : load, then execute
|||
activate "Wica-JS-Library"
"Wica-JS-Library" -> "Web Page HTML"  : scan web page
activate "Web Page HTML"
return // wica channel names and properties//
|||
"Wica-JS-Library" -> "Wica-HTTP-Server" : create wica stream ( // config data// )
activate "Wica-HTTP-Server"
    "Wica-HTTP-Server" -> "Control System" : monitor //points-of-interest//
return //stream_id//
deactivate "Wica-JS-Library"
|||
end
|||
group process: acquire data
    "Wica-HTTP-Server" -> "Control System" : poll //points-of-interest//
    return //polled values//
        "Control System" -> "Wica-HTTP-Server" : //monitored values//
    "Wica-HTTP-Server" -> "Wica-HTTP-Server" : buffer values
end
|||
"Wica-JS-Library" -> "Wica-HTTP-Server" : subscribe wica stream  ( //stream_id// )
activate "Wica-JS-Library"
activate "Wica-HTTP-Server"
group process: handle event stream messages
    "Wica-HTTP-Server" -> "Wica-JS-Library" : SSE message stream ( //metadata, values, heartbeat...// )
    "Wica-JS-Library" -> "Web Page DOM" : update wica element: //attributes//
    "Wica-JS-Library" -> "Web Page DOM" : update wica element: //text content//
    "Wica-JS-Library" -> "Web Page DOM" : update wica element: //generate events//
|||
end
note left: Messages are sent\nat configurable\nperiodic intervals
deactivate "Wica-JS-Library"
deactivate "Wica-HTTP-Server"
|||
group process: repaint
    "Browser" -> "Web Page DOM" : read
    "Browser" -> "Web Page HTML" : process  events
    activate "Web Page HTML"
    return //done//
    note right: Run JS
    "Browser" -> "Browser" : repaint page
end

@enduml
